# Mission-level configuration
mission:
  max_search_iterations: 30
  search_timeout_seconds: 300

# Logging configuration
logging:
  log_dir: logs
  max_logs: 50

# --- REFACTORED: Define the 3-drone P2P fleet ---
# As described in the COBALT document [cite: 8]
drones:
  - id: scout_1
    type: simulated
    [cite_start]role: scout  # [cite: 10]
  - id: payload_1
    type: simulated
    [cite_start]role: payload # [cite: 15]
  - id: utility_1
    type: simulated
    [cite_start]role: utility # [cite: 20]

# MQTT configuration (for Hub and Drones)
mqtt:
  host: localhost
  port: 1883
  base_topic: "cobalt/vessel_42" # Use a base topic

# GCS Server configuration (run by Tier 2 Hub)
gcs:
  host: "0.0.0.0"
  port: 8765

# ... (Camera, Detection, Health configs remain the same) ...
cameras:
  thermal:
    type: simulated
    resolution: [160, 120]
    water_temp: 15.0
    ambient_temp: 20.0
    intrinsics: { width: 160, height: 120, focal_length_x: 120, focal_length_y: 120, principal_point_x: 80, principal_point_y: 60 }
  
  visual:
    type: simulated
    resolution: [640, 480]
    intrinsics: { width: 640, height: 480, focal_length_x: 400, focal_length_y: 400, principal_point_x: 320, principal_point_y: 240 }
  
  recording:
    enabled: true
    output_dir: recordings

detection:
  method: fusion
  thermal:
    temp_threshold: 10.0
    min_area: 50
    max_area: 500
    min_confidence: 0.5
  visual:
    use_color: true
    use_motion: true
    min_confidence: 0.6
  fusion:
    thermal_weight: 0.7
    visual_weight: 0.3
    fusion_threshold: 0.75
    max_position_error: 50

health:
  min_battery_preflight: 50.0
  min_battery_emergency: 20.0
  [cite_start]min_battery_patrol_rtl: 30.0 # [cite: 88]
  max_heartbeat_latency: 5.0

# ... (Strategy configs remain the same) ...
strategies:
  search:
    algorithm: lawnmower # Default for utility/scout-assist
    area:
      x: 0.0
      y: 0.0
      z: 0.0
    size: 1000.0
  flight:
    algorithm: direct

# --- NEW: Config block for Probabilistic AI (Item 5) ---
[cite_start]# [cite: 57]
prob_search:
    grid_size: 100
    search_area_size_m: 2000.0
    search_altitude: 100.0
    
    # Sensor model parameters from patent
    r_max: 500.0
    h_ref: 50.0
    miss_probability: 0.1
    
    # AI Control Loop parameters
    evolve_interval_s: 5.0
    waypoint_interval_s: 10.0
    drift_x_m_s: 0.5
    drift_y_m_s: 0.2

vertical_ascent:
  max_altitude: 150.0
  step_size: 5.0
precision_hover:
  altitude_offset: 2.0
lawnmower:
  patrol_altitude: 40.0
  spacing: 50.0
  leg_length: 500.0
  num_legs: 10
orbit:
  radius: 100.0
  speed: 10.0
  altitude_offset: 30.0